CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL
);

CREATE TABLE Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL,
    taken_at timestamp,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    library_id int REFERENCES Library(id) On DELETE SET NULL
);

CREATE TABLE City(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) UNIQUE NOT NULL
);

CREATE TABLE Library(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) UNIQUE NOT NULL,
    address varchar(100) UNIQUE NOT NULL,
    city_id int REFERENCES City(id) ON DELETE SET NULL
);

drop table Person;
drop table Book;

alter table book add column taken_at timestamp;